---
- hosts: ubuntu-test-srv-1
  tasks:
    - name: Fetch the file from test-srv-1 to buffer
      fetch:
        src: /tmp/test.txt
        dest: buffer/
        flat: yes

    - name: Transfer the buffer to test-srv-2
      delegate_to: ubuntu-test-srv-2
      copy:
        src: buffer/test.txt
        dest: /tmp/
