---
- hosts: all
  tasks:
    - name: Copy the file from test-srv-1 to buffer
      run_once: yes
      copy:
        src: /tmp/test.txt
        dest: buffer/
        flat: yes
      when: "{{ inventory_hostname == 'ubuntu-test-srv-1' }}"

    - name: Copy the file from buffer to test-srv-2
      copy:
        src: buffer/test.txt
        dest: /tmp/
      when: "{{ inventory_hostname == 'ubuntu-test-srv-2' }}"
