---
- name: Copy host inventory information to AWX server
  hosts: all
  tasks:
    - name: Copy file to AWX server
      copy:
        src: /tmp/{{ inventory_hostname }}_inventory_information.txt
        dest: /tmp/awx-host-info/{{ inventory_hostname }}_inventory_information.txt
      delegate_to: andy-awxnode-test
      become: false
