---
- name: Copy inventory information file from host to AWX server
  hosts: all
  gather_facts: no

  tasks:
  - name: Get hostname
    shell: hostname
    register: hostname_result

  - name: Copy file to AWX server
    copy:
      src: /tmp/{{ hostname_result.stdout }}_inventory_information.txt
      dest: /home/ansible_andy/awx-host-info/{{ hostname_result.stdout }}_inventory_information.txt
      remote_src: yes
