---
- name: Copy host inventory information file
  hosts: all
  tasks:
    - name: Copy host information file
      copy:
        src: "/tmp/{{ inventory_hostname }}_inventory_information.txt"
        dest: "/tmp/awx-host-info/{{ inventory_hostname }}_inventory_information.txt"
