---
- name: Copy file from one host to another
  hosts: ubuntu-test-srv-1
  gather_facts: no
  tasks:
    - name: Copy file from source host
      copy:
        src: /tmp/test.txt
        dest: /tmp/
        remote_src: yes

- name: Copy file to destination host
  hosts: ubuntu-test-srv-2
  gather_facts: no
  tasks:
    - name: Copy file to destination
      copy:
        src: /tmp/test.txt
        dest: /tmp/
