---
- name: Copy inventory information file from host to AWX server
  hosts: all
  gather_facts: yes
  
  tasks:
  - name: Get hostname
    set_fact:
      hostname: "{{ ansible_nodename }}"

  - name: Copy file to AWX server
    copy:
      src: /tmp/"{{ hostname }}"_inventory_information.txt
      dest: ~/awx-host-info/{{ hostname }}_inventory_information.txt
