---
#NOT WORKING - APPEARS TO BE ATTEMPTING TO COPY TO HOST DIRECTORY AND NOT AWX
#SEE PREVIOUS COMMITS
- name: Copy inventory information file from host to AWX server
  hosts: all
  become: yes
  become_user: root
  gather_facts: no

  tasks:
  - name: Get hostname
    shell: hostname
    register: hostname_result

  - name: Copy file to AWX server
    local_action:
      module: fetch
      src: /tmp/{{ hostname_result.stdout }}_inventory_information.txt
      dest: /tmp/awx-host-info/{{ hostname_result.stdout }}_inventory_information.txt
      flat: yes
      become: yes
      become_user: root
